#ifndef WIREWORLD2D_WIREWORLDFIELDTYPES_H
#define WIREWORLD2D_WIREWORLDFIELDTYPES_H

#include "Field.h"

enum TCell {
    EMPTY_CELL, ELECTRON_TAIL, ELECTRON_HEAD, CONDUCTOR
};

using TField = Field<TCell>;

#endif //WIREWORLD2D_WIREWORLDFIELDTYPES_H
