#ifndef WIREWORLD2D_WIREWORLDFIELDTYPES_H
#define WIREWORLD2D_WIREWORLDFIELDTYPES_H

#include "VectorField.h"

enum class TWireWorldCell {
    EMPTY_CELL, ELECTRON_TAIL, ELECTRON_HEAD,
    CONDUCTOR
};

using TField = VectorField<TWireWorldCell>;

#endif //WIREWORLD2D_WIREWORLDFIELDTYPES_H
