#ifndef PRISONER_DILEMMA_PRISONERDILEMMAUNITTESTS_H
#define PRISONER_DILEMMA_PRISONERDILEMMAUNITTESTS_H

#include "gtest/gtest.h"

int RunTests(int argc, char *argv[]);

#endif //PRISONER_DILEMMA_PRISONERDILEMMAUNITTESTS_H
